// ── js/emoji-data.js — Emoji catalog with categories for picker ──

export const EMOJI_CATEGORIES = [
  { id: 'recent', icon: '🕐', label: 'Недавние', emojis: [] },
  { id: 'smileys', icon: '😀', label: 'Смайлы', emojis: [
    { e: '😀', n: 'grinning happy smile' }, { e: '😃', n: 'smiley happy' }, { e: '😄', n: 'smile happy laugh' },
    { e: '😁', n: 'grin beam' }, { e: '😆', n: 'laughing satisfied' }, { e: '😅', n: 'sweat smile awkward' },
    { e: '🤣', n: 'rofl rolling laugh' }, { e: '😂', n: 'joy tears laugh' }, { e: '🙂', n: 'slightly smile' },
    { e: '😉', n: 'wink' }, { e: '😊', n: 'blush happy shy' }, { e: '😇', n: 'innocent angel halo' },
    { e: '🥰', n: 'love hearts face' }, { e: '😍', n: 'heart eyes love' }, { e: '🤩', n: 'star struck excited' },
    { e: '😘', n: 'kiss blow' }, { e: '😜', n: 'wink tongue playful' }, { e: '🤔', n: 'thinking hmm' },
    { e: '🤗', n: 'hugging warm' }, { e: '🤫', n: 'shushing quiet secret' }, { e: '🤭', n: 'giggle oops' },
    { e: '😐', n: 'neutral blank' }, { e: '😑', n: 'expressionless' }, { e: '😶', n: 'no mouth silent' },
    { e: '😏', n: 'smirk sly' }, { e: '😒', n: 'unamused annoyed' }, { e: '🙄', n: 'eye roll' },
    { e: '😤', n: 'angry steam huff' }, { e: '😠', n: 'angry mad' }, { e: '😡', n: 'rage furious red' },
    { e: '😢', n: 'cry sad tear' }, { e: '😭', n: 'sob crying loud' }, { e: '😱', n: 'scream shock horror' },
    { e: '😴', n: 'sleeping zzz' }, { e: '🤮', n: 'vomit sick' }, { e: '🥳', n: 'party celebrate' },
    { e: '😎', n: 'cool sunglasses' }, { e: '🤓', n: 'nerd glasses' }, { e: '🥺', n: 'pleading puppy eyes' },
    { e: '💀', n: 'skull dead' }, { e: '👻', n: 'ghost boo' },
  ]},
  { id: 'people', icon: '👋', label: 'Люди', emojis: [
    { e: '👋', n: 'wave hello hi bye' }, { e: '🤚', n: 'raised back hand' }, { e: '✋', n: 'raised hand stop' },
    { e: '🖖', n: 'vulcan spock' }, { e: '👌', n: 'ok perfect' }, { e: '🤌', n: 'pinched italian' },
    { e: '✌️', n: 'victory peace' }, { e: '🤞', n: 'crossed fingers luck' }, { e: '🫰', n: 'hand heart finger' },
    { e: '👍', n: 'thumbs up good yes' }, { e: '👎', n: 'thumbs down bad no' }, { e: '👊', n: 'fist bump punch' },
    { e: '✊', n: 'raised fist power' }, { e: '🤝', n: 'handshake deal agree' }, { e: '🙏', n: 'pray please thanks' },
    { e: '💪', n: 'strong muscle flex' }, { e: '👀', n: 'eyes look see' }, { e: '👁️', n: 'eye single' },
    { e: '👤', n: 'person silhouette user' }, { e: '👥', n: 'people group team' }, { e: '🧑‍💻', n: 'developer coder programmer' },
    { e: '👨‍💼', n: 'office worker business' }, { e: '👩‍🎓', n: 'student graduate' }, { e: '🧑‍🔬', n: 'scientist researcher' },
    { e: '👩‍🍳', n: 'chef cook' }, { e: '🧑‍🎨', n: 'artist painter' }, { e: '🧑‍🏫', n: 'teacher professor' },
    { e: '🧑‍⚕️', n: 'doctor health' }, { e: '🦸', n: 'superhero' }, { e: '🧘', n: 'meditation yoga zen' },
  ]},
  { id: 'nature', icon: '🌿', label: 'Природа', emojis: [
    { e: '🐶', n: 'dog puppy' }, { e: '🐱', n: 'cat kitten' }, { e: '🐭', n: 'mouse' },
    { e: '🐰', n: 'rabbit bunny' }, { e: '🦊', n: 'fox clever' }, { e: '🐻', n: 'bear' },
    { e: '🐼', n: 'panda' }, { e: '🐨', n: 'koala' }, { e: '🦁', n: 'lion king' },
    { e: '🐸', n: 'frog' }, { e: '🐝', n: 'bee honey' }, { e: '🦋', n: 'butterfly' },
    { e: '🌸', n: 'cherry blossom flower pink' }, { e: '🌹', n: 'rose red flower' }, { e: '🌻', n: 'sunflower' },
    { e: '🌺', n: 'hibiscus flower' }, { e: '🌿', n: 'herb leaf green' }, { e: '🍀', n: 'clover luck four leaf' },
    { e: '🌲', n: 'evergreen tree pine' }, { e: '🌴', n: 'palm tree tropical' }, { e: '🌵', n: 'cactus desert' },
    { e: '🍄', n: 'mushroom' }, { e: '🌈', n: 'rainbow' }, { e: '⚡', n: 'lightning bolt zap electric' },
    { e: '🔥', n: 'fire hot flame lit' }, { e: '💧', n: 'water drop' }, { e: '🌊', n: 'wave ocean sea' },
    { e: '❄️', n: 'snowflake cold winter' }, { e: '☀️', n: 'sun sunny bright' }, { e: '🌙', n: 'moon crescent night' },
    { e: '⭐', n: 'star yellow' }, { e: '🌟', n: 'glowing star sparkle shine' }, { e: '✨', n: 'sparkles magic' },
  ]},
  { id: 'food', icon: '🍔', label: 'Еда', emojis: [
    { e: '🍎', n: 'apple red fruit' }, { e: '🍊', n: 'orange tangerine' }, { e: '🍋', n: 'lemon yellow' },
    { e: '🍇', n: 'grapes purple' }, { e: '🍓', n: 'strawberry berry' }, { e: '🍑', n: 'peach' },
    { e: '🍌', n: 'banana' }, { e: '🥑', n: 'avocado' }, { e: '🥕', n: 'carrot' },
    { e: '🌽', n: 'corn' }, { e: '🍕', n: 'pizza slice' }, { e: '🍔', n: 'burger hamburger' },
    { e: '🍟', n: 'fries french' }, { e: '🌮', n: 'taco mexican' }, { e: '🍣', n: 'sushi japanese' },
    { e: '🍜', n: 'ramen noodles soup' }, { e: '🍝', n: 'spaghetti pasta' }, { e: '🍰', n: 'cake dessert' },
    { e: '🍩', n: 'doughnut donut sweet' }, { e: '🍪', n: 'cookie biscuit' }, { e: '🍫', n: 'chocolate bar' },
    { e: '☕', n: 'coffee hot drink' }, { e: '🍵', n: 'tea green matcha' }, { e: '🧃', n: 'juice box' },
    { e: '🍺', n: 'beer mug' }, { e: '🍷', n: 'wine glass red' }, { e: '🥤', n: 'cup straw drink' },
  ]},
  { id: 'activities', icon: '⚽', label: 'Активности', emojis: [
    { e: '⚽', n: 'soccer football' }, { e: '🏀', n: 'basketball' }, { e: '🏈', n: 'football american' },
    { e: '⚾', n: 'baseball' }, { e: '🎾', n: 'tennis' }, { e: '🏐', n: 'volleyball' },
    { e: '🏋️', n: 'weight lifting gym' }, { e: '🧗', n: 'climbing' }, { e: '🚴', n: 'cycling bike' },
    { e: '🏊', n: 'swimming pool' }, { e: '🧘', n: 'yoga meditation' }, { e: '🏃', n: 'running jogging' },
    { e: '🎮', n: 'game controller gaming' }, { e: '🕹️', n: 'joystick arcade' }, { e: '🎲', n: 'dice game' },
    { e: '♟️', n: 'chess pawn strategy' }, { e: '🎯', n: 'target dart bullseye goal' }, { e: '🎳', n: 'bowling' },
    { e: '🎨', n: 'art palette paint creative' }, { e: '🎬', n: 'movie film clapper' }, { e: '🎤', n: 'microphone karaoke sing' },
    { e: '🎧', n: 'headphones music listen' }, { e: '🎵', n: 'music note song' }, { e: '🎹', n: 'piano keyboard music' },
    { e: '🎸', n: 'guitar rock music' }, { e: '📸', n: 'camera photo' }, { e: '🏆', n: 'trophy winner champion' },
    { e: '🥇', n: 'gold medal first' }, { e: '🥈', n: 'silver medal second' }, { e: '🥉', n: 'bronze medal third' },
  ]},
  { id: 'travel', icon: '✈️', label: 'Места', emojis: [
    { e: '🏠', n: 'house home' }, { e: '🏢', n: 'office building' }, { e: '🏫', n: 'school university' },
    { e: '🏥', n: 'hospital' }, { e: '🏪', n: 'store shop convenience' }, { e: '🏛️', n: 'classical building museum' },
    { e: '⛪', n: 'church' }, { e: '🕌', n: 'mosque' }, { e: '🏰', n: 'castle european' },
    { e: '🗼', n: 'tower tokyo' }, { e: '🌍', n: 'globe earth world europe africa' }, { e: '🌏', n: 'globe asia' },
    { e: '🗺️', n: 'map world' }, { e: '🚗', n: 'car automobile' }, { e: '🚕', n: 'taxi cab' },
    { e: '🚌', n: 'bus' }, { e: '🚂', n: 'train locomotive' }, { e: '✈️', n: 'airplane plane travel fly' },
    { e: '🚀', n: 'rocket launch space' }, { e: '🛸', n: 'ufo flying saucer' }, { e: '⛵', n: 'sailboat' },
    { e: '🏖️', n: 'beach umbrella vacation' }, { e: '🏔️', n: 'mountain snow' }, { e: '⛺', n: 'tent camping' },
  ]},
  { id: 'objects', icon: '💡', label: 'Объекты', emojis: [
    { e: '💡', n: 'light bulb idea' }, { e: '🔧', n: 'wrench tool fix' }, { e: '🔨', n: 'hammer build' },
    { e: '⚙️', n: 'gear settings config' }, { e: '🔑', n: 'key password' }, { e: '🔒', n: 'lock secure private' },
    { e: '🔓', n: 'unlock open' }, { e: '📱', n: 'phone mobile smartphone' }, { e: '💻', n: 'laptop computer' },
    { e: '🖥️', n: 'desktop monitor screen' }, { e: '⌨️', n: 'keyboard typing' }, { e: '🖨️', n: 'printer' },
    { e: '📷', n: 'camera photo' }, { e: '📹', n: 'video camera record' }, { e: '📺', n: 'tv television' },
    { e: '📻', n: 'radio' }, { e: '⏰', n: 'alarm clock time' }, { e: '⏱️', n: 'stopwatch timer' },
    { e: '📄', n: 'page document file' }, { e: '📝', n: 'memo note write' }, { e: '📋', n: 'clipboard list' },
    { e: '📌', n: 'pin pushpin' }, { e: '📎', n: 'paperclip attach' }, { e: '📁', n: 'folder directory' },
    { e: '📚', n: 'books stack library' }, { e: '📖', n: 'book open read' }, { e: '📊', n: 'chart bar graph stats' },
    { e: '📈', n: 'chart up growth trending' }, { e: '📉', n: 'chart down decline' }, { e: '🗂️', n: 'card index files organize' },
    { e: '💰', n: 'money bag rich' }, { e: '💳', n: 'credit card payment' }, { e: '💎', n: 'gem diamond jewel' },
    { e: '🎁', n: 'gift present' }, { e: '📦', n: 'package box delivery' }, { e: '🏷️', n: 'label tag price' },
  ]},
  { id: 'symbols', icon: '✅', label: 'Символы', emojis: [
    { e: '❤️', n: 'red heart love' }, { e: '🧡', n: 'orange heart' }, { e: '💛', n: 'yellow heart' },
    { e: '💚', n: 'green heart' }, { e: '💙', n: 'blue heart' }, { e: '💜', n: 'purple heart' },
    { e: '🖤', n: 'black heart' }, { e: '🤍', n: 'white heart' }, { e: '💔', n: 'broken heart' },
    { e: '✅', n: 'check done complete yes' }, { e: '❌', n: 'cross no wrong cancel' }, { e: '⭕', n: 'circle hollow' },
    { e: '❗', n: 'exclamation important alert' }, { e: '❓', n: 'question help' }, { e: '⚠️', n: 'warning caution' },
    { e: '🚫', n: 'prohibited forbidden no' }, { e: '♻️', n: 'recycle' }, { e: '💬', n: 'speech bubble comment chat' },
    { e: '💭', n: 'thought bubble think' }, { e: '🔔', n: 'bell notification alert' }, { e: '🔕', n: 'bell mute silent' },
    { e: '📅', n: 'calendar date' }, { e: '📆', n: 'tearoff calendar' }, { e: '🔗', n: 'link chain url' },
    { e: '➕', n: 'plus add' }, { e: '➖', n: 'minus subtract' }, { e: '➗', n: 'divide division' },
    { e: '♾️', n: 'infinity forever' }, { e: '💯', n: 'hundred perfect score' }, { e: '🏁', n: 'checkered flag finish race' },
  ]},
];
